
_inputs:
  center-content:
    type: html
  color-scheme:
    type: number
  bottom-text:
    type: text

_structures:
  bg-video:
    values:
      - value:
          ideo_path: /uploads/sea-24216-540p.mp4
          type: video/mp4
  cols:
    values:
      - value:
          heading: col Heading
          text_alinment: center
          paragraph: Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto perferendis quas quibusdam, voluptatibus pariatur totam vitae soluta eum amet, deleniti error quidem voluptatum vel aliquam. Voluptatem reiciendis doloribus quis iste?
          img_path: https://picsum.photos/id/1020/600/400
          img_alt: bear pic
          button_text: text
          button_link: #
  blocks:
    values:
      - label: Video banner
        value:
          _id: video-banner
          center-content: >
                        <img src="/logo.png" class="mx-auto max-w-sm"> 
                        <h2 class="uppercase  text-center text-xl">Opening in Summer 2024 </h2> 
                        <a href="#apply" class="uppercase  border-white py-2 px-4"> get on the list </a>
          color-scheme: 1
          bg-video:
            - video_path: /uploads/sea-24216-540p.mp4
              type: mp4
          bottom-text: Scrool down to discover
      - label: Basic col section
        value:
          _id: col-section-basic
          heading: Basic heading
          pre-heading: Pre heading text
          paragraph: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          cols:
          text_alignment: center
          color-scheme: 1