
_inputs:
  block-content-html:
    type: html
    options:
      format: p h2 h3 a img
      styles: /editor.css
      left: text-left
      center: text-center
      right: text-right
  center-content:
    type: html
  color-scheme:
    type: number
  bottom-text:
    type: text
  img_apsect: 
    type: select
    options:
      values:
        1: Square 
        2/4: Portraight 
        4/3: Landscape
        default: Images Native
  img-position:
    type: select
    options:
      values:
        - left
        - right
  heading_style:
    type: select
    option:
      values:
        heading-1: large 
        heading-2: subtle
  min-height:
    type: select
    option:
      values:
        50vh: half screen min-min
        75vh: three quater screen min-min
        90vh: just short of full screen
        100vh: full screen
  button_style:
    type: select
    options:
      values:
        button: normal
        button-featured: featured
_structures:
  bg-video:
    values:
      - value:
          ideo_path: /uploads/sea-24216-540p.mp4
          type: video/mp4
  cols:
    values:
      - value:
          heading: col Heading
          text_alinment: center
          paragraph: Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto perferendis quas quibusdam, voluptatibus pariatur totam vitae soluta eum amet, deleniti error quidem voluptatum vel aliquam. Voluptatem reiciendis doloribus quis iste?
          img_path: https://picsum.photos/id/1020/600/400
          img_alt: bear pic
          button_text: text
          button_link: #
  imgs:
    values:
    - value:
        img_path: https://picsum.photos/id/1020/600/400
        img_alt: text describing the image
        img_apsect: square
  blocks:
    values:
      - label: Video banner
        value:
          _id: video-banner
          block-content-html: >-
                        <p><img class="mx-auto max-w-sm" src="/logo.png" /></p><h3 class="heading-1">Opening in Summer 2024</h3><p><a class="button-featured" href="#apply">get on the list </a></p>
          color-scheme: 1
          bg-video:
            - video_path: /uploads/sea-24216-540p.mp4
              type: mp4
          bottom-text: Scroll down to discover
      - label: Banner with side image
        value:
          _id: sidebanner
          heading: our community 
          color-scheme: 1
          img:
            img_path: https://picsum.photos/id/1020/600/400
            img_alt: text describing the image
            img_apsect: square
          bottom-text: Scrool down to discover
          img-position: right
          img_width_percentage: 60%
          block-content-html: >
            <a href="#apply" class="uppercase border-white py-2 px-4"> get on the list </a>
      - label: Basic col section
        value:
          _id: col-section-basic
          heading: Basic heading
          pre-heading: Pre heading text
          paragraph: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          cols:
            - heading: Suite
              heading_style:
              text_alinment: center
              paragraph: >-
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                perferendis quas quibusdam, voluptatibus pariatur totam vitae soluta
                eum amet, deleniti error quidem voluptatum vel aliquam. Voluptatem
                reiciendis doloribus quis iste?
              img_path: https://picsum.photos/id/1020/600/400
              img_alt: bear pic
              button_text: text
              button_link:
          image_default_ratio: false
          text_alignment: center
          color-scheme: 1
      - label: Horizontal screen gallery
        value:
          _id: horizontal-screen-gallery
          heading: Basic heading
          pre-heading: Pre heading text
          paragraph: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          imgs:
            - img_path:  "https://picsum.photos/id/1020/600/400"
              img_alt: text describing the image
              img_apsect: 2/4
            - img_path: |
                  https://picsum.photos/id/1020/600/400
              img_alt: text describing the image
              img_apsect: 2/4
            - img_path: |
                  https://picsum.photos/id/1020/600/400
              img_alt: text describing the image
              img_apsect: 2/4
          image_default_ratio: true
          text_alignment: center
          color-scheme: 1