
collections:
  accomodations:
    output: true
    permalink: /:title
  rooms:
    output: false
    permalink: /:title
  experiences:
    output: true
  events:
    output: true


url: "https://example.com" # the base hostname & protocol for your site
gem:
  - jekyll-sitemap