












_inputs:
  center-content:
    type: html
  color-scheme:
    type: number
  bottom-text:
    type: text

_structures:
  bg-video:
    values:
      - value:
          ideo_path: /uploads/sea-24216-540p.mp4
          type: video/mp4

  blocks:
    values:
      - label: Video banner
        value:
          _id: video-banner
          center-content: >
                        <img src="/logo.png" class="mx-auto max-w-sm"> 
                        <h2 class="uppercase  text-center text-xl">Opening in Summer 2024 </h2> 
                        <a href="#apply" class="uppercase  border-white py-2 px-4"> get on the list </a>
          color-scheme: 1
          bg-video:
            - video_path: /uploads/sea-24216-540p.mp4
              type: mp4
          bottom-text: Scrool down to discover